Refactored tests for fracture mesh generation
pmgbergen/porepy pull request #1024
Opened 2023-10-13 11:57 UTC by keileg

## Proposed changes
* Moved various tests for fracture mesh generation to new locations.
* Expanded tests for structured mesh generation in fractured domains
* Maintenance and improvements of tests

## Types of changes

What types of changes does this PR introduce to PorePy?
_Put an `x` in the boxes that apply._

- [ ] Minor change (e.g., dependency bumps, broken links).
- [ ] Bugfix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [x] Testing (contribution related to testing of existing or new functionality).
- [x] Documentation (contribution related to adding, improving, or fixing documentation).
- [x] Maintenance (e.g., improve logic and performance, remove obsolete code).
- [ ] Other:

## Checklist

_Put an `x` in the boxes that apply or explain briefly why the box is not relevant._

- [x] The documentation is up-to-date.
- [x] Static typing is included in the update.
- [x] This PR does not duplicate existing functionality.
- [x] The update is covered by the test suite (including tests added in the PR).
- [ ] If new skipped tests have been introduced in this PR, `pytest` was run with the `--run-skipped` flag.

2023-10-13 14:03 UTC, IvarStefansson requested changes
Nice work. I made some improvements, please review carefully. Also left some comments, please ask if you need me to elaborate/want to discuss.

2023-10-16 10:41 UTC, keileg commented on tests/fracs/test_fracture_network_3d.py
> +    # expected values. To construct the grid bounding boxes,
Improved documentation.

2023-10-16 10:41 UTC, keileg commented on tests/fracs/test_fracture_network_3d.py
> +        mdg = _create_mdg([f_1], domain)
Checks will be introduced.

2023-10-16 10:42 UTC, keileg commented on tests/fracs/test_fracture_network_3d.py
> +    """Tests similar to some those of the mother class, but with some fractures as
Updated.

2023-10-16 11:10 UTC, keileg commented
Thanks for the improvements, @IvarStefansson, some of them slipped off my radar. I believe the changes just committed should take care of your requests.

2023-10-16 12:25 UTC, IvarStefansson approved these changes
Approving, provided you reviewed my changes.

2023-10-16 12:29 UTC, keileg commented
I did (eventually); they all made sense. Thanks.

2023-10-16 12:29 UTC, merged