Make code compatible with scipy v1.13
pmgbergen/porepy pull request #1141
Opened 2024-04-03 10:28 UTC by keileg

## Proposed changes
Updates:
1. Disabled two tests related to the coarsening module. The scipy update permuted the output of what is essentially a sparse.find, leading the test to fail a comparison with a known truth. As the coarsening moduleis deprecated, thus fixing the tests was not prioritized. 
2. Enforce integer format of grid topology information. 

## Types of changes

What types of changes does this PR introduce to PorePy?
_Put an `x` in the boxes that apply._

- [ ] Minor change (e.g., dependency bumps, broken links).
- [x] Bugfix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [x] Testing (contribution related to testing of existing or new functionality).
- [ ] Documentation (contribution related to adding, improving, or fixing documentation).
- [ ] Maintenance (e.g., improve logic and performance, remove obsolete code).
- [ ] Other:

## Checklist

_Put an `x` in the boxes that apply or explain briefly why the box is not relevant._

- [x] The documentation is up-to-date.
- [x] Static typing is included in the update.
- [x] This PR does not duplicate existing functionality.
- [x] The update is covered by the test suite (including tests added in the PR).
- [ ] If new skipped tests have been introduced in this PR, `pytest` was run with the `--run-skipped` flag.

2024-04-03 12:41 UTC, IvarStefansson reviewed
Seems good to me. I'll defer to @OmarDuran, though. He has a better understanding of this than me.

2024-04-03 12:41 UTC, IvarStefansson commented on src/porepy/grids/simplex.py
> -            dtype=float,
Interesting!

2024-04-04 07:57 UTC, OmarDuran requested changes
@keileg thank you for enforcing types in topological information. The only suggestion I have is to implement a test that checks that the topological information is indeed an integer for all the grids.

2024-04-04 09:46 UTC, OmarDuran commented
> > @keileg thank you for enforcing types in topological information. The only suggestion I have is to implement a test that checks that the topological information is indeed an integer for all the grids.
> 
> I'm not sure if I agree: The attributes will be `int`s now and remain so unless we remove that line, which is highly unlikely. Moreover, it is not a disaster if the attributes become floats again - the previous code worked perfectly fine for several years. I realize that sparse find etc. may be less stable for floats, but again, this will not happen unless we revert the code.
> 
> So, I would say the benefits of testing this feature do not warrant the cost of dealing with extra tests. Do you agree, or have I missed something?

In addition to being a suggestion, keep in mind that tracking types correctly correlates with code stability. Nevertheless, I agree with you that as long as users do not mess with types associated with topology, these changes are sufficient.

2024-04-04 11:17 UTC, merged