Tutorial updates
pmgbergen/porepy pull request #680
Opened 2022-07-20 13:38 UTC by IvarStefansson

## Proposed changes

Overhaul of tutorials. Tutorials are removed, renamed and reworked. The remaining ones should give a decent, up-to-date introduction to PorePy.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Testing (contribution related mainly to testing of existing functionality)
- [x] Documentation update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR._
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation 
- [x] I have checked that I have not duplicated existing functionality

## Further comments

Main updates are related to AD. Note the summary provided in the readme.

2022-07-24 13:02 UTC, jhabriel requested changes
Superb job in updating the tutorials.

I requested some minor changes. After these are addressed, I'll be happy to approve the merging.

Although I don't think this is necessary for this particular PR. I do believe some restructuring of the tutorials is needed. By restructuring, I mean organizing them in separate (sub)directories based on whether they are meant as introductory, technical, advanced, benchmarking (I'm working on these for poroelasticity), or legacy tutorials (which might as well be called deprecated).

2022-07-25 08:37 UTC, IvarStefansson commented on tutorials/Readme.md
> +4. [algorithmic_differentiation](./algorithmic_differentiation.ipynb) provides an introduction to algorithmic differentiation (AD) and how to solve a generic equation using the AD framework. The tuto
This was @jwboth's suggestion. Could you remind us of the rationale, please?

2022-07-25 08:37 UTC, IvarStefansson commented on tutorials/flux_discretizations.ipynb
> +    "The multi-point flux approximation also solves the single-phase flow problem in the primal formulation. We discretize the flux term anew with the MPFA, and assemble the matrix. Note that the cal
That could be a solution, yes. Opinions, @keileg?

2022-08-01 07:27 UTC, keileg commented on tutorials/Readme.md
> +4. [algorithmic_differentiation](./algorithmic_differentiation.ipynb) provides an introduction to algorithmic differentiation (AD) and how to solve a generic equation using the AD framework. The tuto
I think this depends on the viewpoint: From the user side it is automatic, whereas to a developer it is certainly not so. I have no strong opinions here besides the comment that using algorithmic will confuse some people.

2022-08-01 07:27 UTC, keileg commented on tutorials/incompressible_flow_model.ipynb
> +    "## What have we explored\n",
I agree.

2022-08-01 07:29 UTC, keileg commented on tutorials/flux_discretizations.ipynb
> +    "The multi-point flux approximation also solves the single-phase flow problem in the primal formulation. We discretize the flux term anew with the MPFA, and assemble the matrix. Note that the cal
I think @jhabriel has a valid point that people will be confused. I'm fine with dropping the primal/dual terminology.

2022-08-01 08:30 UTC, keileg commented on tutorials/incompressible_flow_model.ipynb
> +    "## What have we explored\n",
@IvarStefansson (@jhabriel): I can draft such summaries where I find it natural, then you can amend. Is that okay?

2022-08-01 08:42 UTC, jwboth commented on tutorials/Readme.md
> +4. [algorithmic_differentiation](./algorithmic_differentiation.ipynb) provides an introduction to algorithmic differentiation (AD) and how to solve a generic equation using the AD framework. The tuto
The first sentence of wikipedia on AD: "In mathematics and computer algebra, automatic differentiation (AD), also called algorithmic differentiation, computational differentiation, auto-differentiation, or simply autodiff, is a set of techniques to evaluate the derivative of a function ..." 

Eirik's guess on the viewpoint is I guess the reason for why there exist different names for it. Whenever I heard someone talking about research on AD, they liked using "algorithmic differentiation" to emphasize that there is no free lunch when you think about linearizing more complex problems (see e.g. contact mechanics), while users indeed like to point out that for them it is "automatic".

After all, I also have no strong opinion how to call AD in the doc of porepy.

2022-08-02 07:58 UTC, keileg approved these changes

2022-08-02 07:59 UTC, keileg commented
I'm fine with merging when @jhabriel's request has been met.

Thanks a lot for the effort, @IvarStefansson!

2022-08-02 08:05 UTC, jhabriel approved these changes

2022-08-02 13:07 UTC, merged